basePath: /auth
definitions:
  utils.ErrorCodeMessage:
    properties:
      code:
        type: string
      message:
        type: string
    type: object
  utils.TelarError:
    properties:
      error:
        $ref: '#/definitions/utils.ErrorCodeMessage'
    type: object
host: social.telar.dev
info:
  contact:
    email: dev@telar.dev
    name: API Support
  description: This is an API to authenticate users
  license:
    name: MIT
    url: https://github.com/red-gold/telar-web/blob/master/LICENSE
  termsOfService: http://swagger.io/terms/
  title: Auth micro API
  version: "1.0"
paths:
  /admin/check:
    post:
      description: handler to check whether admin user registered
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - type: object
            - properties:
                admin:
                  type: boolean
              type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/utils.TelarError'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/utils.TelarError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/utils.TelarError'
      summary: whether admin user registered
swagger: "2.0"
